name: gnnip2
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.7.2=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.14=h80987f9_0
  - pip=24.0=py310hca03da5_0
  - python=3.10.14=hb885b13_1
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.43.0=py310hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - annotated-types==0.7.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - filelock==3.15.4
      - fsspec==2024.6.1
      - idna==3.7
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.0.1
      - pandas==2.2.2
      - psutil==6.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - scipy==1.14.0
      - six==1.16.0
      - sympy==1.13.1
      - torch==2.3.0
      - torchdata==0.7.1
      - tqdm==4.66.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
# prefix: /Users/haihaosun/anaconda3/envs/gnnip2
